import {
  Bookmark,
  Paperclip,
  Folder,
  FolderBookmark,
  FolderClosed,
  FolderOpen,
  Folders,
  FileStack,
  FileQuestionMark,
  FileImage,
  BookImage,
  Image,
  Images,
  Gpu,
  MirrorRectangular,
  Sun,
  Moon,
  Cloud,
  CloudFog,
  CloudDrizzle,
  CloudSun,
  Cloudy,
  Apple,
  Coffee,
  Cookie,
  ChefHat,
  Sandwich,
  BottleWine,
  Clover,
  Club,
  Crown,
  Gem,
  Gift,
  Headphones,
  Rocket,
  Star,
  Ghost,
  House,
  Heart,
  Flower,
  Leaf,
  Sprout,
  Trees,
  MapPin,
  Utensils,
  ShipWheel,
  Bell,
  AlarmClock,
  Album,
  FlaskConical,
  Snowflake,
  Cylinder,
  Mail,
  Palette,
  Trash2,
  type LucideIcon,
} from 'lucide-react'

// Mirrors the backend's folder icon allowlist (see backend/internal/usecase/folder_icon.go).
// Unrecognized keys fall back to the default `folder` icon (see iconForKey below).
export const FOLDER_ICONS: Record<string, LucideIcon> = {
  bookmark: Bookmark,
  paperclip: Paperclip,
  folder: Folder,
  'folder-bookmark': FolderBookmark,
  'folder-closed': FolderClosed,
  'folder-open': FolderOpen,
  folders: Folders,
  'file-stack': FileStack,
  'file-question-mark': FileQuestionMark,
  'file-image': FileImage,
  'book-image': BookImage,
  image: Image,
  images: Images,
  gpu: Gpu,
  'mirror-rectangular': MirrorRectangular,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-fog': CloudFog,
  'cloud-drizzle': CloudDrizzle,
  'cloud-sun': CloudSun,
  cloudy: Cloudy,
  apple: Apple,
  coffee: Coffee,
  cookie: Cookie,
  'chef-hat': ChefHat,
  sandwich: Sandwich,
  'bottle-wine': BottleWine,
  clover: Clover,
  club: Club,
  crown: Crown,
  gem: Gem,
  gift: Gift,
  headphones: Headphones,
  rocket: Rocket,
  star: Star,
  ghost: Ghost,
  house: House,
  heart: Heart,
  flower: Flower,
  leaf: Leaf,
  sprout: Sprout,
  trees: Trees,
  'map-pin': MapPin,
  utensils: Utensils,
  'ship-wheel': ShipWheel,
  bell: Bell,
  'alarm-clock': AlarmClock,
  album: Album,
  'flask-conical': FlaskConical,
  snowflake: Snowflake,
  cylinder: Cylinder,
  mail: Mail,
  palette: Palette,
  'trash-2': Trash2,
}

export const DEFAULT_FOLDER_ICON_KEY = 'folder'
export const SYSTEM_ICON_KEYS = {
  all: 'file-stack',
  unsorted: 'file-question-mark',
  trash: 'trash-2',
} as const

export function iconForKey(key: string | null | undefined): LucideIcon {
  if (key && FOLDER_ICONS[key]) return FOLDER_ICONS[key]
  return FOLDER_ICONS[DEFAULT_FOLDER_ICON_KEY]
}
